parameters:
    coresphere_console.toolbar.class: CoreSphere\ConsoleBundle\DataCollector\DataCollector

services:
    coresphere_console.toolbar:
        class: %coresphere_console.toolbar.class%
        tags:
            - { name: data_collector, template: "CoreSphereConsoleBundle:Toolbar:toolbar", id: "coresphere_console" }
